### ISSUE TITLE
je kan een groter element een font meegeven zodat het bij kleinere elementen al wordt meegegeven

### ISSUE THREAD

**Issue by SamaraFellaDina** [wingsvn/server-side-rendering-server-side-website#3]
zo hoef je het ook minder op te schrijven scheelt tijd en regels ;)

```css
body {
    font-family: var(--font-sans-serif);
    padding: 0;
    margin: 0;
}
```
